name: ai_mobile_ensar_islami
description: AI mobile app with Supabase authentication
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env


